topology:
  queues:
    - name: "queue"

  topics:
    - name: "events"
      subscriptions:
        - name: sub-1
          filters:
            - type: correlation
              properties:
                region: "us-east"
        - name: sub-2
          filters:
            - type: correlation
              subject: "order-created"
        - name: sub-3
